// GENERATED by regen-data.mjs from scripts/fx.json — do not hand-edit.
export const FX_USD_INR = 95.12 as const
export const FX_AS_OF = "2026-08-14" as const
export const FX_SOURCE = "Repo-standardized planning rate (standardized Aug 14, 2026; not a live quote). Refresh from the RBI/FBIL USD-INR reference rate for the current date, update as_of, then recompute." as const
